@hostname=localhost:5280

GET {{hostname}}/book/
Accept: application/json

###
GET {{hostname}}/author
Accept: application/json

###
GET {{hostname}}/publisher
Accept: application/json

###
GET {{hostname}}/category
Accept: application/json

###
GET {{hostname}}/borrow
Accept: application/json